# indxing and selection

In [2]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[8]

8

In [12]:
arr[1:5]

array([1, 2, 3, 4])

In [14]:
arr[:5]

array([0, 1, 2, 3, 4])

In [16]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

# NumPy Broadcasting

In [21]:
arr[0:5] = 100

In [23]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [37]:
slice_of_arr =  arr[0:5]

In [39]:
slice_of_arr[:] = 99

In [41]:
slice_of_arr[:] 

array([99, 99, 99, 99, 99])

# Indexing on IID arrays

In [50]:
arr2D = np.array([[5,10,15],[20,25,30],[30,40,40]])

In [54]:
arr2D 

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 40, 40]])

In [60]:
arr2D.shape

(3, 3)

In [62]:
arr2D[0]

array([ 5, 10, 15])