# NumPy Arrays

In [2]:
import numpy as np

In [4]:
list = [1,2,3]

In [6]:
type(list)

list

In [8]:
np.array(list)

array([1, 2, 3])

In [12]:
arr = np.array(list)

In [14]:
type(arr)

numpy.ndarray

In [16]:
matrix = [[1,2,4],[1,3,4],[2,3,4]]

In [18]:
np.array(matrix)

array([[1, 2, 4],
       [1, 3, 4],
       [2, 3, 4]])

In [24]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

# Useful functions

In [33]:
len(np.linspace(0,10,3))

3

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
np.random.rand(1)

array([0.13464816])

In [41]:
np.random.randn(10)

array([-0.62956777,  0.05508618,  0.59750912,  0.69764088,  0.33121324,
       -1.20211281,  0.22979856, -0.43301484,  0.36009872, -1.32706938])

In [45]:
np.random.randint(0,20,20)

array([ 4, 19,  6, 14,  9, 17, 17,  0, 12,  7,  4, 10,  5, 10,  3, 16,  5,
        4,  4, 15])

In [51]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [73]:
arrr = np.arange(0,25)

In [75]:
arrr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])