# Numpy Operations

In [2]:
import numpy as np

In [6]:
arr =  np.arange (0,10)

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Adding array by an array

In [20]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [24]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
# arr/arr gives an error

# Universal Array functions

In [35]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [37]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [39]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [41]:
arr.sum()

45